---
title: "us_tilapia_imports"
author: "zachyloo"
date: "2025-08-15"
output: html_document
---

# United States Tilapia Imports

```{r}
library(tidyverse)
library(here)
library(janitor)
```

```{r}
# read data
us_tilapia_imports <- read_csv(here::here("data/us_tilapia_imports.csv"))
```

```{r}
# explore data
names(us_tilapia_imports)
summary(us_tilapia_imports)
skimr::skim(us_tilapia_imports)
```

```{r}
# pivot into long df
us_tilapia_imports_long <- us_tilapia_imports |> 
  pivot_longer(cols = -country, 
               names_to = "year")

# change year col to numeric
us_tilapia_imports_long <- us_tilapia_imports_long |> 
  mutate(year = as.numeric(year))
```

```{r}
# find total US imports by year 
yearly_tilapia_tot <- us_tilapia_imports_long |> 
  group_by(year) |> # squish all 'years' together into ONE row
  summarize(us_import_value = sum(value, na.rm = TRUE))
```

```{r}
# plot dat
library(ggtext)
ggplot(data = yearly_tilapia_tot, aes(x = year, y = us_import_value)) + 
  geom_line(color = "red", linewidth = 1) +
  theme_light() +
  labs(title = "US Tilapia Imports by Year",
       x = "Year",
       y = "Tilapia Import Amount (x10<sup>3</sup> Pounds)") +
  theme(axis.title.y = element_markdown())
```

```{r}
# save plot
ggsave(here::here("figs", "us_tilapia_import.png"), height = 6, width = 7)
```


```{r}
# ecuador, honduras, costa rica, mexico subset 
country_list <- c("Ecuador", "Honduras", "Costa Rica", "Mexico")

tilapia_long_subset <- us_tilapia_imports_long |> 
  dplyr::filter(country == country_list)
```

```{r}
# plot four lines for each country, representing us imports from each country
ggplot(data = tilapia_long_subset, aes(x = year, y = value)) + 
  geom_line(aes(color = country), linewidth = 1) + # display four lines for each country
  theme_light() +
  labs(title = "US Tilapia Imports by Selected Countries Over Time",
       x = "Year",
       y = "Tilapia Import Amount (x10<sup>3</sup> Pounds)") +
  theme(axis.title.y = element_markdown())

```

```{r}
# save plot
ggsave(here::here("figs", "imports_by_country.png"), height = 6, width = 7)
```

